<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDhOtYZP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDhOtYZP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDhOtYZP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDhOtYZP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDhOtYZP\App_KernelDevDebugContainer([
    'container.build_hash' => 'DhOtYZP',
    'container.build_id' => '5f38f0b2',
    'container.build_time' => 1619431032,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDhOtYZP');
